export const BRANCHES = [
  'Asheville',
  'Atlanta',
  'Birmingham',
  'Cape Girardeau',
  'Chattanooga',
  'Columbus',
  'Destin',
  'Huntsville',
  'Jackson, MS',
  'Jackson, TN',
  'Jacksonville',
  'Jonesboro',
  'Knoxville',
  'Lake Charles',
  'Little Rock',
  'Louisville',
  'Memphis',
  'Mobile',
  'Montgomery',
  'Nashville',
  'New Orleans',
  'Norfolk',
  'Raleigh',
  'Richmond',
  'San Antonio',
  'Savannah',
  'St. Louis',
  'Tallahassee',
  'Wilmington',
] as const;
